#!/bin/sh

FILE1=/tmp/linuxtranslate1-$$
FILE2=/tmp/linuxtranslate2-$$
FILE3=/tmp/linuxtranslate3-$$
FILE4=/tmp/linuxtranslate3-$$
ERROR=/tmp/linuxtranslate-err-$$

HOST=localhost
PORT=1239
MODE=local

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

GETTEXT="gettext -d linuxtranslate_ui"

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}


helpMsg () {
	echo "Usage: $0 [ --network | --help ]" 
	exit -1
}

if [ $# -eq 0 ]
then
MODE=local
elif [ $# -eq 1 ]
then
        if [ $1 = '--help' ]
        then
                helpMsg
                exit -1
        elif [ $1 = '--network' ]
	then
                MODE=network
        fi

fi



while true
do
	#Another way of displaying the words, with --inputbox
	#$DIALOG --inputbox "`cat $FILE3` \\n\\n `$GETTEXT \"Pick a word and enter his number\"`" 0 0 2> $FILE1 || end

	WORDS=`curl -s "http://semes-olla.rhcloud.com/words?Swadesh/English.py" | sed s/'([^)]*)'/''/g | sed s/'<[^)]*>'/''/g | tr '\n' ',' | tr '|' ','`
	IFS=',' read -a words <<< "$WORDS"
	$DIALOG --title "Select a word to be translated" --menu "Choose an option" 20 78 16 \
	"${words[@]}" 2> $FILE1

        INDEX=`cat $FILE1`

	if [ $MODE = 'local' ]
	then
		echo ModeLocal
		curl -s "http://semes-olla.rhcloud.com/word?`cat $FILE1`&Swadesh/Slavic/Macedonian.py" > $FILE2
		if [ -s "$FILE2" ]
		then
		MSG="`$GETTEXT \"The Macedonian translation\"` `cat $FILE2`. Continue?"
		$DIALOG --yesno "$MSG" 0 0 || end
		else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 0 0 || end
		fi
		
	elif [ $MODE = 'network' ]
	then
		echo ModeNetwork
		LINUXTRANSLATE="nc $HOST $PORT"
		echo $INDEX | $LINUXTRANSLATE > $FILE2 2> $ERROR
		if [ -s "$FILE2" ]
		then
		MSG="`$GETTEXT \"The Macedonian translation\"` `cat $FILE2`. Continue?"
		$DIALOG --yesno "$MSG" 0 0 || end
		else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 0 0 || end
		fi
	fi

done

